[project]
name = "apple-notes"
version = "0.1.0"
description = "A Python API to interact with Apple's Notes app."
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
apple-notes = "apple_notes.__main__:main"

[tool.pytest.ini_options]
pythonpath = ["."]
